name: ci

on: ["push"]
.0
jobs:
  docker-build:
    runs-on: ubuntu-latest
    steps:
       - name: checkout
         uses: actions/checkout@v2.7.0
       - name: verify
         run: ls
       - name: Docker Login
         uses: docker/login-action@v2.1.0
         with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
       - name: Build and push Docker image
         uses: docker/build-push-action@v4.0.0
         with:
          push: true
          tags: ElDamoss/getting-started:latest
